### ISSUE TITLE
Module 10 help

### ISSUE THREAD

**Issue by jlevart** [GeekTrainer/Introduction-Programming-Python#5]
Hello!
I'm new to programming and was having some difficulty with the challenge for module 10.  When I tried to load the solution for the challenge, I kept getting an error about the project being not found.  Upon closer inspection of the file, I noticed that the extension is ".sln" and not ".py".  Is there anyway that the ".py" file could be uploaded?

P.S.  Excellent series!!!

**Comment by emmanuelmacharia** [comment]
.snl  files are solution files for Visual Studio. So, I'd  recommend that you have visual studio installed.
Alternatively, if you don't want VS, download the files themselves (.py) and leave the entire solution alone; then you can have open them with your preferred text editor

**Comment by jlevart** [comment]
I am using VS, and it cannot open the .sln file.  I was asking for the .py
file to be uploaded.

**Comment by emmanuelmacharia** [comment]
what was the challenge?
I could upload my solution file.. see if that could help
there wasn't one-  so you can work with mine
Or you can head to https://github.com/emmanuelmacharia/Introduction-Programming-Python and checkout the file called day2MVAworkingwithlists.py

**Comment by jlevart** [comment]
Thanks for your help.  Got it straightened out after a bit more research.
